"""Mock SPLC (Supply Chain Analysis) data, served by GET /v1/splc.

Field names match the SPLCApiResponse contract (TargetCompany/SupplierNode/
CustomerNode/CompetitorNode) from the Supply Chain dashboard's backend
integration spec, plus a few extra fields (oneYearPerformancePct, riskScore,
sector on suppliers/customers) that the frontend's Inspector panel and matrix
table already render -- the contract itself is a minimum, not a ceiling.

This is a straight Python port of frontend/src/data/mockSupplyChainData.js.
Swapping this out for a real data source (SEC EDGAR / Financial Modeling
Prep / a supply-chain vendor) only requires changing get_splc_dataset()
below -- the router (splc.py) and the frontend adapter
(frontend/src/api/supplyChain.js's transformSplcResponse) don't need to
change as long as the returned shape matches.
"""
from __future__ import annotations

from typing import Any


def _b(usd_billions: float) -> float:
    """Convert a $B figure (as used in the frontend mock data) to raw USD."""
    return usd_billions * 1_000_000_000


def _m(usd_millions: float) -> float:
    """Convert a $M figure to raw USD."""
    return usd_millions * 1_000_000


_AAPL: dict[str, Any] = {
    "symbol": "AAPL",
    "name": "Apple Inc.",
    "sector": "Technology Hardware",
    "industry": "Consumer Electronics",
    "marketCap": _b(3450),
    "oneYearPerformancePct": 24.8,
    "suppliers": [
        {
            "symbol": "TSM",
            "name": "Taiwan Semiconductor Mfg.",
            "relationshipType": "Sole-Source Chip Foundry (A-series / M-series SoCs)",
            "revenueExposurePercent": 22,
            "cogsExposurePercent": 18,
            "estimatedValueUSD": _m(19500),
            "disclosureSource": "SEC Form 10-K, Item 1 (Customer Concentration)",
            "marketCap": _b(720),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 61.2,
            "riskScore": "High",
        },
        {
            "symbol": "2317.TW",
            "name": "Foxconn / Hon Hai Precision",
            "relationshipType": "Primary Final-Assembly (iPhone/iPad/Mac EMS)",
            "revenueExposurePercent": 52,
            "cogsExposurePercent": 45,
            "estimatedValueUSD": _m(68000),
            "disclosureSource": "Trade Shipment Manifest (Import Genius) + 10-K",
            "marketCap": _b(68),
            "sector": "Electronics Manufacturing Services",
            "oneYearPerformancePct": 38.4,
            "riskScore": "High",
        },
        {
            "symbol": "QCOM",
            "name": "Qualcomm Inc.",
            "relationshipType": "Cellular Modem / RF Supplier (Snapdragon X)",
            "revenueExposurePercent": 8,
            "cogsExposurePercent": 6,
            "estimatedValueUSD": _m(3200),
            "disclosureSource": "SEC Form 10-K, Item 1",
            "marketCap": _b(195),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 12.1,
            "riskScore": "Medium",
        },
        {
            "symbol": "SWKS",
            "name": "Skyworks Solutions",
            "relationshipType": "RF Front-End Module Supplier",
            "revenueExposurePercent": 65,
            "cogsExposurePercent": 4,
            "estimatedValueUSD": _m(1750),
            "disclosureSource": "SEC Form 10-K, Item 1 (Customer Concentration)",
            "marketCap": _b(12),
            "sector": "Semiconductors",
            "oneYearPerformancePct": -9.7,
            "riskScore": "Medium",
        },
        {
            "symbol": "SONY",
            "name": "Sony Group Corp.",
            "relationshipType": "CMOS Image Sensor Supplier (Camera Modules)",
            "revenueExposurePercent": 13,
            "cogsExposurePercent": 5,
            "estimatedValueUSD": _m(2100),
            "disclosureSource": "Analyst Estimate (Nikkei supply-chain survey)",
            "marketCap": _b(135),
            "sector": "Consumer Electronics",
            "oneYearPerformancePct": 29.6,
            "riskScore": "Low",
        },
    ],
    "customers": [
        {
            "symbol": "BBY",
            "name": "Best Buy Co.",
            "relationshipType": "Retail Distribution Channel",
            "revenueExposurePercent": 5,
            "estimatedValueUSD": _m(19000),
            "disclosureSource": "Analyst Estimate (channel-checks)",
            "marketCap": _b(18),
            "sector": "Specialty Retail",
            "oneYearPerformancePct": 4.3,
            "riskScore": "Low",
        },
        {
            "symbol": "AMZN",
            "name": "Amazon.com Inc.",
            "relationshipType": "Retail Distribution Channel (Marketplace + 1P)",
            "revenueExposurePercent": 7,
            "estimatedValueUSD": _m(26500),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(1980),
            "sector": "Internet Retail",
            "oneYearPerformancePct": 44.1,
            "riskScore": "Low",
        },
        {
            "symbol": "VZ",
            "name": "Verizon Communications",
            "relationshipType": "Carrier Channel / Device Financing Partner",
            "revenueExposurePercent": 6,
            "estimatedValueUSD": _m(22700),
            "disclosureSource": "Analyst Estimate (carrier sell-through data)",
            "marketCap": _b(175),
            "sector": "Telecom Services",
            "oneYearPerformancePct": 15.8,
            "riskScore": "Low",
        },
        {
            "symbol": "T",
            "name": "AT&T Inc.",
            "relationshipType": "Carrier Channel / Device Financing Partner",
            "revenueExposurePercent": 5,
            "estimatedValueUSD": _m(18900),
            "disclosureSource": "Analyst Estimate (carrier sell-through data)",
            "marketCap": _b(162),
            "sector": "Telecom Services",
            "oneYearPerformancePct": 9.2,
            "riskScore": "Low",
        },
    ],
    "competitors": [
        {
            "symbol": "SSNLF",
            "name": "Samsung Electronics",
            "overlapSector": "Technology Hardware",
            "relationshipType": "Direct Competitor (Smartphones, Wearables)",
            "marketCap": _b(385),
            "oneYearPerformancePct": 11.4,
            "riskScore": "Low",
        },
        {
            "symbol": "MSFT",
            "name": "Microsoft Corp.",
            "overlapSector": "Software & Services",
            "relationshipType": "Direct Competitor (PC/Tablet OS, Services)",
            "marketCap": _b(3120),
            "oneYearPerformancePct": 21.9,
            "riskScore": "Low",
        },
        {
            "symbol": "GOOGL",
            "name": "Alphabet Inc.",
            "overlapSector": "Interactive Media",
            "relationshipType": "Direct Competitor (Mobile OS, Services)",
            "marketCap": _b(2240),
            "oneYearPerformancePct": 33.5,
            "riskScore": "Low",
        },
    ],
}

_NVDA: dict[str, Any] = {
    "symbol": "NVDA",
    "name": "NVIDIA Corp.",
    "sector": "Semiconductors",
    "industry": "Semiconductors",
    "marketCap": _b(3280),
    "oneYearPerformancePct": 178.3,
    "suppliers": [
        {
            "symbol": "TSM",
            "name": "Taiwan Semiconductor Mfg.",
            "relationshipType": "Sole-Source Foundry (CoWoS / 4N Process)",
            "revenueExposurePercent": 11,
            "cogsExposurePercent": 55,
            "estimatedValueUSD": _m(14200),
            "disclosureSource": "SEC Form 10-K, Item 1",
            "marketCap": _b(720),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 61.2,
            "riskScore": "High",
        },
        {
            "symbol": "000660.KS",
            "name": "SK Hynix Inc.",
            "relationshipType": "HBM3E Memory Supplier",
            "revenueExposurePercent": 18,
            "cogsExposurePercent": 20,
            "estimatedValueUSD": _m(8600),
            "disclosureSource": "Analyst Estimate (supply-chain checks)",
            "marketCap": _b(92),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 68.9,
            "riskScore": "High",
        },
        {
            "symbol": "2317.TW",
            "name": "Foxconn / Hon Hai Precision",
            "relationshipType": "GPU Server Rack Assembly (GB200 NVL72)",
            "revenueExposurePercent": 6,
            "cogsExposurePercent": 9,
            "estimatedValueUSD": _m(5100),
            "disclosureSource": "Trade Shipment Manifest",
            "marketCap": _b(68),
            "sector": "Electronics Manufacturing Services",
            "oneYearPerformancePct": 38.4,
            "riskScore": "Medium",
        },
    ],
    "customers": [
        {
            "symbol": "MSFT",
            "name": "Microsoft Corp.",
            "relationshipType": "Hyperscaler / AI Infrastructure Buyer",
            "revenueExposurePercent": 19,
            "estimatedValueUSD": _m(24500),
            "disclosureSource": "SEC Form 10-K, Item 1 (Customer Concentration)",
            "marketCap": _b(3120),
            "sector": "Software & Services",
            "oneYearPerformancePct": 21.9,
            "riskScore": "Medium",
        },
        {
            "symbol": "META",
            "name": "Meta Platforms Inc.",
            "relationshipType": "Hyperscaler / AI Infrastructure Buyer",
            "revenueExposurePercent": 14,
            "estimatedValueUSD": _m(18100),
            "disclosureSource": "SEC Form 10-K, Item 1 (Customer Concentration)",
            "marketCap": _b(1450),
            "sector": "Interactive Media",
            "oneYearPerformancePct": 41.2,
            "riskScore": "Medium",
        },
        {
            "symbol": "AMZN",
            "name": "Amazon.com Inc. (AWS)",
            "relationshipType": "Hyperscaler / AI Infrastructure Buyer",
            "revenueExposurePercent": 12,
            "estimatedValueUSD": _m(15600),
            "disclosureSource": "SEC Form 10-K, Item 1 (Customer Concentration)",
            "marketCap": _b(1980),
            "sector": "Internet Retail",
            "oneYearPerformancePct": 44.1,
            "riskScore": "Medium",
        },
    ],
    "competitors": [
        {
            "symbol": "AMD",
            "name": "Advanced Micro Devices",
            "overlapSector": "Semiconductors",
            "relationshipType": "Direct Competitor (GPU / Data Center Accelerators)",
            "marketCap": _b(225),
            "oneYearPerformancePct": -6.8,
            "riskScore": "Low",
        },
        {
            "symbol": "INTC",
            "name": "Intel Corp.",
            "overlapSector": "Semiconductors",
            "relationshipType": "Direct Competitor (Data Center Accelerators)",
            "marketCap": _b(98),
            "oneYearPerformancePct": -22.4,
            "riskScore": "Low",
        },
    ],
}

_TSLA: dict[str, Any] = {
    "symbol": "TSLA",
    "name": "Tesla Inc.",
    "sector": "Automobiles",
    "industry": "Auto Manufacturers",
    "marketCap": _b(1080),
    "oneYearPerformancePct": 8.6,
    "suppliers": [
        {
            "symbol": "6752.T",
            "name": "Panasonic Holdings",
            "relationshipType": "Battery Cell Supplier (2170/4680 co-production)",
            "revenueExposurePercent": 9,
            "cogsExposurePercent": 15,
            "estimatedValueUSD": _m(4300),
            "disclosureSource": "SEC Form 10-K, Item 1",
            "marketCap": _b(38),
            "sector": "Consumer Electronics",
            "oneYearPerformancePct": 6.1,
            "riskScore": "Medium",
        },
        {
            "symbol": "300750.SZ",
            "name": "Contemporary Amperex (CATL)",
            "relationshipType": "LFP Battery Cell Supplier",
            "revenueExposurePercent": 7,
            "cogsExposurePercent": 12,
            "estimatedValueUSD": _m(3600),
            "disclosureSource": "Analyst Estimate (supply-chain checks)",
            "marketCap": _b(145),
            "sector": "Battery Manufacturing",
            "oneYearPerformancePct": 19.3,
            "riskScore": "Medium",
        },
        {
            "symbol": "ALB",
            "name": "Albemarle Corp.",
            "relationshipType": "Lithium / Raw Materials Supplier",
            "revenueExposurePercent": 4,
            "cogsExposurePercent": 5,
            "estimatedValueUSD": _m(900),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(11),
            "sector": "Specialty Chemicals",
            "oneYearPerformancePct": -18.7,
            "riskScore": "Low",
        },
    ],
    "customers": [
        {
            "symbol": "HTZ",
            "name": "Hertz Global Holdings",
            "relationshipType": "Fleet Buyer",
            "revenueExposurePercent": 2,
            "estimatedValueUSD": _m(700),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(3),
            "sector": "Rental & Leasing",
            "oneYearPerformancePct": -12.9,
            "riskScore": "Low",
        },
    ],
    "competitors": [
        {
            "symbol": "BYDDY",
            "name": "BYD Company Ltd.",
            "overlapSector": "Automobiles",
            "relationshipType": "Direct Competitor (BEV/PHEV)",
            "marketCap": _b(105),
            "oneYearPerformancePct": 52.7,
            "riskScore": "Low",
        },
        {
            "symbol": "RIVN",
            "name": "Rivian Automotive",
            "overlapSector": "Automobiles",
            "relationshipType": "Direct Competitor (BEV)",
            "marketCap": _b(14),
            "oneYearPerformancePct": -4.2,
            "riskScore": "Low",
        },
        {
            "symbol": "F",
            "name": "Ford Motor Co.",
            "overlapSector": "Automobiles",
            "relationshipType": "Direct Competitor (BEV segment)",
            "marketCap": _b(42),
            "oneYearPerformancePct": -7.5,
            "riskScore": "Low",
        },
    ],
}

_MSFT: dict[str, Any] = {
    "symbol": "MSFT",
    "name": "Microsoft Corp.",
    "sector": "Software & Services",
    "industry": "Software - Infrastructure",
    "marketCap": _b(3120),
    "oneYearPerformancePct": 21.9,
    "suppliers": [
        {
            "symbol": "NVDA",
            "name": "NVIDIA Corp.",
            "relationshipType": "AI Accelerator / GPU Supplier (Azure)",
            "revenueExposurePercent": 19,
            "cogsExposurePercent": 10,
            "estimatedValueUSD": _m(24500),
            "disclosureSource": "Analyst Estimate (capex disclosures)",
            "marketCap": _b(3280),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 178.3,
            "riskScore": "High",
        },
        {
            "symbol": "AMD",
            "name": "Advanced Micro Devices",
            "relationshipType": "Secondary AI Accelerator Supplier (Azure)",
            "revenueExposurePercent": 6,
            "cogsExposurePercent": 3,
            "estimatedValueUSD": _m(3100),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(225),
            "sector": "Semiconductors",
            "oneYearPerformancePct": -6.8,
            "riskScore": "Medium",
        },
    ],
    "customers": [
        {
            "symbol": "ACN",
            "name": "Accenture plc",
            "relationshipType": "Enterprise Reseller / Systems Integrator",
            "revenueExposurePercent": 4,
            "estimatedValueUSD": _m(9800),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(190),
            "sector": "IT Services",
            "oneYearPerformancePct": -2.3,
            "riskScore": "Low",
        },
    ],
    "competitors": [
        {
            "symbol": "AAPL",
            "name": "Apple Inc.",
            "overlapSector": "Technology Hardware",
            "relationshipType": "Direct Competitor (OS, Devices, Services)",
            "marketCap": _b(3450),
            "oneYearPerformancePct": 24.8,
            "riskScore": "Low",
        },
        {
            "symbol": "GOOGL",
            "name": "Alphabet Inc.",
            "overlapSector": "Interactive Media",
            "relationshipType": "Direct Competitor (Cloud, Productivity, AI)",
            "marketCap": _b(2240),
            "oneYearPerformancePct": 33.5,
            "riskScore": "Low",
        },
        {
            "symbol": "AMZN",
            "name": "Amazon.com Inc. (AWS)",
            "overlapSector": "Internet Retail",
            "relationshipType": "Direct Competitor (Cloud Infrastructure)",
            "marketCap": _b(1980),
            "oneYearPerformancePct": 44.1,
            "riskScore": "Low",
        },
    ],
}

_AMD: dict[str, Any] = {
    "symbol": "AMD",
    "name": "Advanced Micro Devices",
    "sector": "Semiconductors",
    "industry": "Semiconductors",
    "marketCap": _b(225),
    "oneYearPerformancePct": -6.8,
    "suppliers": [
        {
            "symbol": "TSM",
            "name": "Taiwan Semiconductor Mfg.",
            "relationshipType": "Sole-Source Foundry (CPU/GPU Dies)",
            "revenueExposurePercent": 4,
            "cogsExposurePercent": 62,
            "estimatedValueUSD": _m(6100),
            "disclosureSource": "SEC Form 10-K, Item 1",
            "marketCap": _b(720),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 61.2,
            "riskScore": "High",
        },
        {
            "symbol": "ASX",
            "name": "ASE Technology Holding",
            "relationshipType": "Chip Packaging & Test (OSAT)",
            "revenueExposurePercent": 5,
            "cogsExposurePercent": 8,
            "estimatedValueUSD": _m(850),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(22),
            "sector": "Semiconductors",
            "oneYearPerformancePct": 4.9,
            "riskScore": "Medium",
        },
    ],
    "customers": [
        {
            "symbol": "MSFT",
            "name": "Microsoft Corp.",
            "relationshipType": "Secondary AI Accelerator Buyer (Azure)",
            "revenueExposurePercent": 9,
            "estimatedValueUSD": _m(3100),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(3120),
            "sector": "Software & Services",
            "oneYearPerformancePct": 21.9,
            "riskScore": "Medium",
        },
        {
            "symbol": "DELL",
            "name": "Dell Technologies",
            "relationshipType": "OEM / Server & PC Integrator",
            "revenueExposurePercent": 7,
            "estimatedValueUSD": _m(2400),
            "disclosureSource": "Analyst Estimate",
            "marketCap": _b(78),
            "sector": "Technology Hardware",
            "oneYearPerformancePct": 3.4,
            "riskScore": "Low",
        },
    ],
    "competitors": [
        {
            "symbol": "NVDA",
            "name": "NVIDIA Corp.",
            "overlapSector": "Semiconductors",
            "relationshipType": "Direct Competitor (GPU / Data Center Accelerators)",
            "marketCap": _b(3280),
            "oneYearPerformancePct": 178.3,
            "riskScore": "Low",
        },
        {
            "symbol": "INTC",
            "name": "Intel Corp.",
            "overlapSector": "Semiconductors",
            "relationshipType": "Direct Competitor (CPU / Data Center)",
            "marketCap": _b(98),
            "oneYearPerformancePct": -22.4,
            "riskScore": "Low",
        },
        {
            "symbol": "QCOM",
            "name": "Qualcomm Inc.",
            "overlapSector": "Semiconductors",
            "relationshipType": "Direct Competitor (Client/Mobile Compute)",
            "marketCap": _b(195),
            "oneYearPerformancePct": 12.1,
            "riskScore": "Low",
        },
    ],
}

SPLC_DATASETS: dict[str, dict[str, Any]] = {
    "AAPL": _AAPL,
    "NVDA": _NVDA,
    "TSLA": _TSLA,
    "MSFT": _MSFT,
    "AMD": _AMD,
}


def get_splc_dataset(symbol: str) -> dict[str, Any] | None:
    """Look up a ticker's SPLC dataset, or None if uncovered."""
    return SPLC_DATASETS.get(symbol.upper())


def supported_symbols() -> list[str]:
    return list(SPLC_DATASETS.keys())
